DROP TABLE IF EXISTS stationnement CASCADE;
DROP TABLE IF EXISTS compte CASCADE;
DROP TABLE IF EXISTS appliquer CASCADE;
DROP TABLE IF EXISTS diviser CASCADE;
DROP TABLE IF EXISTS proposer_auv CASCADE;
DROP TABLE IF EXISTS posseder_au CASCADE;
DROP TABLE IF EXISTS posseder_av CASCADE;
DROP TABLE IF EXISTS place CASCADE;
DROP TABLE IF EXISTS vehicule CASCADE;
DROP TABLE IF EXISTS abonnement CASCADE;
DROP TABLE IF EXISTS parking CASCADE;
DROP TABLE IF EXISTS creneau CASCADE;
DROP TABLE IF EXISTS tarif CASCADE;
DROP TABLE IF EXISTS categorie_place CASCADE;
DROP TABLE IF EXISTS utilisateur CASCADE;
DROP TABLE IF EXISTS commune CASCADE;

-- Drop custom types
DROP TYPE IF EXISTS genre_type CASCADE;
DROP TYPE IF EXISTS genre_abonnement CASCADE;